// Generated by CoffeeScript 1.4.0
(function() {

  $(function() {
    new ScheudulePicker('#scheudule_picker');
    return new ScheudulePicker('#inline_scheudule_picker', {
      inline: true
    });
  });

}).call(this);
