// Generated by CoffeeScript 1.4.0
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  this.unique_id = function(length) {
    var id;
    if (length == null) {
      length = 8;
    }
    id = "";
    while (id.length < length) {
      id += Math.random().toString(36).substr(2);
    }
    return id.substr(0, length);
  };

  this.ScheudulePicker = (function() {

    function ScheudulePicker(selector, args) {
      this.args = args != null ? args : {};
      this.add_row_with_values = __bind(this.add_row_with_values, this);

      this.add_row = __bind(this.add_row, this);

      this.val = __bind(this.val, this);

      this.get_json_values = __bind(this.get_json_values, this);

      this.ok = __bind(this.ok, this);

      this.show_picker = __bind(this.show_picker, this);

      this.input = $(selector);
      this.id = 'scheudule_picker_' + unique_id();
      this.change_markup();
    }

    ScheudulePicker.prototype.change_markup = function() {
      if (this.args.inline) {
        this.input.after(this.create_picker());
        $('.scheudule_picker_ok', this.picker).hide();
        return $('input', this.picker).change(function() {
          return console.log('kct');
        });
      } else {
        return this.input.before(this.create_selector());
      }
    };

    ScheudulePicker.prototype.create_selector = function() {
      this.selector = $(this.create_selector_markup());
      this.selector.click(this.show_picker);
      return this.selector;
    };

    ScheudulePicker.prototype.create_selector_markup = function() {
      return '<input type="button" class="scheudule_picker_selector" value="Select Scheudule" />';
    };

    ScheudulePicker.prototype.show_picker = function() {
      if (this.picker != null) {
        return this.picker.fadeIn();
      } else {
        return this.create_picker();
      }
    };

    ScheudulePicker.prototype.create_picker = function() {
      this.picker = this.create_picker_markup();
      this.picker.hide();
      this.input.after(this.picker);
      this.check_for_previous_value();
      $('.scheudule_picker_add_row', this.picker).click(this.add_row);
      $('.scheudule_picker_ok', this.picker).click(this.ok);
      $('tbody', this.picker).on('click', '.scheudule_picker_remove_row', this.remove_row);
      return this.show_picker();
    };

    ScheudulePicker.prototype.check_for_previous_value = function() {
      var json, prev_val;
      prev_val = this.input.val();
      try {
        json = JSON.parse(prev_val);
        return this.val(json);
      } catch (_error) {}
    };

    ScheudulePicker.prototype.remove_row = function(e) {
      return $(e.target).parents('tr').remove();
    };

    ScheudulePicker.prototype.ok = function() {
      var json;
      json = this.get_json_values();
      this.input.val(json);
      if (!this.args.inline) {
        return this.picker.fadeOut();
      }
    };

    ScheudulePicker.prototype.get_json_values = function() {
      return JSON.stringify(this.val());
    };

    ScheudulePicker.prototype.val = function(arg) {
      if (arg == null) {
        arg = null;
      }
      if (arg === null) {
        return this.get_value();
      } else {
        return this.set_value(arg);
      }
    };

    ScheudulePicker.prototype.set_value = function(value) {
      var row, _i, _len, _results;
      _results = [];
      for (_i = 0, _len = value.length; _i < _len; _i++) {
        row = value[_i];
        _results.push(this.add_row_with_values(row));
      }
      return _results;
    };

    ScheudulePicker.prototype.get_value = function() {
      var val;
      val = [];
      $('tbody tr', this.picker).each(function() {
        var row, tr;
        tr = $(this);
        row = {};
        row.time = $('input[data-scheudule-rel=time]', tr).val();
        row.days = [];
        $('[type=checkbox]', tr).each(function() {
          var cb;
          cb = $(this);
          if (cb.is(':checked')) {
            return row.days.push(cb.attr('data-scheudule-rel'));
          }
        });
        return val.push(row);
      });
      return val;
    };

    ScheudulePicker.prototype.add_row = function() {
      return $('tbody', this.picker).append(this.create_row_markup());
    };

    ScheudulePicker.prototype.add_row_with_values = function(values) {
      return $('tbody', this.picker).append(this.create_row_markup(values));
    };

    ScheudulePicker.prototype.parse_row_markup_values = function(values) {
      var i, ret, _i, _len, _ref;
      ret = {
        time: '',
        cb0: '',
        cb1: '',
        cb2: '',
        cb3: '',
        cb4: '',
        cb5: '',
        cb6: ''
      };
      if (values === null) {
        return ret;
      }
      ret.time = values.time;
      _ref = values.days;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        i = _ref[_i];
        ret['cb' + i] = 'checked="checked"';
      }
      return ret;
    };

    ScheudulePicker.prototype.create_row_markup = function(values) {
      var html, i, _i;
      if (values == null) {
        values = null;
      }
      values = this.parse_row_markup_values(values);
      html = '\
    <tr>\
      <td><input type="text" data-scheudule-rel="time" value="' + values.time + '" ></td>';
      for (i = _i = 0; _i <= 6; i = ++_i) {
        html += '<td><input type="checkbox" ' + values['cb' + i] + ' data-scheudule-rel="' + i + '"/></td>';
      }
      return html += '\
      <td><a href="#" class="scheudule_picker_remove_row"> remove </a></td>\
    </tr>';
    };

    ScheudulePicker.prototype.create_picker_markup = function() {
      var html;
      return html = $('<div class="scheudule_picker_wrapper" id="' + this.id + '">\
                <table>\
                  <thead>\
                    <tr>\
                      <th></th>\
                      <th>Sun</th>\
                      <th>Mon</th>\
                      <th>Tue</th>\
                      <th>Wed</th>\
                      <th>Thu</th>\
                      <th>Fri</th>\
                      <th>Sat</th>\
                      <th></th>\
                    </tr>\
                  </thead>\
                  <tbody>\
                  </tbody>\
                  <tfoot>\
                    <tr>\
                      <td>\
                      </td>\
                      <td colspan="7">\
                        <input type="button" class="scheudule_picker_add_row" value="Add row" />\
                      </td>\
                      <td>\
                        <input type="button" class="scheudule_picker_ok" value="Ok" />\
                      </td>\
                    </tr>\
                  </tfoot>\
                </table>\
              </div>');
    };

    return ScheudulePicker;

  })();

}).call(this);
